//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_end.Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Front-end.Shared.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        public static string worksPage {
            get {
                return ResourceManager.GetString("worksPage", resourceCulture);
            }
        }
        
        public static string tutorialsPage {
            get {
                return ResourceManager.GetString("tutorialsPage", resourceCulture);
            }
        }
        
        public static string exhibitionsPage {
            get {
                return ResourceManager.GetString("exhibitionsPage", resourceCulture);
            }
        }
        
        public static string aboutUsPage {
            get {
                return ResourceManager.GetString("aboutUsPage", resourceCulture);
            }
        }
        
        public static string homeSlogan {
            get {
                return ResourceManager.GetString("homeSlogan", resourceCulture);
            }
        }
        
        public static string mission {
            get {
                return ResourceManager.GetString("mission", resourceCulture);
            }
        }
        
        public static string missionSloganPart1 {
            get {
                return ResourceManager.GetString("missionSloganPart1", resourceCulture);
            }
        }
        
        public static string missionSloganPart2 {
            get {
                return ResourceManager.GetString("missionSloganPart2", resourceCulture);
            }
        }
        
        public static string missionSloganPart3 {
            get {
                return ResourceManager.GetString("missionSloganPart3", resourceCulture);
            }
        }
        
        public static string artists {
            get {
                return ResourceManager.GetString("artists", resourceCulture);
            }
        }
        
        public static string homeQuote {
            get {
                return ResourceManager.GetString("homeQuote", resourceCulture);
            }
        }
        
        public static string worksPagePass {
            get {
                return ResourceManager.GetString("worksPagePass", resourceCulture);
            }
        }
        
        public static string seeWorks {
            get {
                return ResourceManager.GetString("seeWorks", resourceCulture);
            }
        }
        
        public static string tutorialsPagePass {
            get {
                return ResourceManager.GetString("tutorialsPagePass", resourceCulture);
            }
        }
        
        public static string exhibitionsPagePass {
            get {
                return ResourceManager.GetString("exhibitionsPagePass", resourceCulture);
            }
        }
        
        public static string tutorialsPagePassSubtitle {
            get {
                return ResourceManager.GetString("tutorialsPagePassSubtitle", resourceCulture);
            }
        }
        
        public static string exhibitionsPagePassSubtitle {
            get {
                return ResourceManager.GetString("exhibitionsPagePassSubtitle", resourceCulture);
            }
        }
        
        public static string partners {
            get {
                return ResourceManager.GetString("partners", resourceCulture);
            }
        }
        
        public static string artistsSpeak {
            get {
                return ResourceManager.GetString("artistsSpeak", resourceCulture);
            }
        }
        
        public static string logoSlogan {
            get {
                return ResourceManager.GetString("logoSlogan", resourceCulture);
            }
        }
        
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        public static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        public static string callUs {
            get {
                return ResourceManager.GetString("callUs", resourceCulture);
            }
        }
        
        public static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        public static string searchPlaceholder {
            get {
                return ResourceManager.GetString("searchPlaceholder", resourceCulture);
            }
        }
        
        public static string ascendingPriceSort {
            get {
                return ResourceManager.GetString("ascendingPriceSort", resourceCulture);
            }
        }
        
        public static string descendingPriceSort {
            get {
                return ResourceManager.GetString("descendingPriceSort", resourceCulture);
            }
        }
        
        public static string minimumPrice {
            get {
                return ResourceManager.GetString("minimumPrice", resourceCulture);
            }
        }
        
        public static string maximumPrice {
            get {
                return ResourceManager.GetString("maximumPrice", resourceCulture);
            }
        }
        
        public static string socialMediaAccounts {
            get {
                return ResourceManager.GetString("socialMediaAccounts", resourceCulture);
            }
        }
        
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        public static string orderForm {
            get {
                return ResourceManager.GetString("orderForm", resourceCulture);
            }
        }
        
        public static string orderFormDescription {
            get {
                return ResourceManager.GetString("orderFormDescription", resourceCulture);
            }
        }
        
        public static string nameField {
            get {
                return ResourceManager.GetString("nameField", resourceCulture);
            }
        }
        
        public static string contactField {
            get {
                return ResourceManager.GetString("contactField", resourceCulture);
            }
        }
        
        public static string emailField {
            get {
                return ResourceManager.GetString("emailField", resourceCulture);
            }
        }
        
        public static string notesField {
            get {
                return ResourceManager.GetString("notesField", resourceCulture);
            }
        }
        
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        public static string nameFieldPlaceholder {
            get {
                return ResourceManager.GetString("nameFieldPlaceholder", resourceCulture);
            }
        }
        
        public static string emailExample {
            get {
                return ResourceManager.GetString("emailExample", resourceCulture);
            }
        }
        
        public static string notesFieldPlaceholder {
            get {
                return ResourceManager.GetString("notesFieldPlaceholder", resourceCulture);
            }
        }
        
        public static string tutorialsPageSlogan {
            get {
                return ResourceManager.GetString("tutorialsPageSlogan", resourceCulture);
            }
        }
    }
}
